-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 12:56:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Appointment` (
  `appointmentId` VARCHAR(10) NOT NULL,
  `patientId` VARCHAR(10) NOT NULL,
  `doctorId` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `patientIssue` JSON NOT NULL,
  `queueNumber` INT NOT NULL,
  `status` ENUM('FINISHED', 'ONGOING') NOT NULL,
  PRIMARY KEY (`appointmentId`, `patientId`, `doctorId`),
  UNIQUE INDEX `appointmentId_UNIQUE` (`appointmentId` ASC) VISIBLE,
  CONSTRAINT `patientId`
    FOREIGN KEY (`patientId`)
    REFERENCES `mydb`.`Patient` (`patientId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `doctorId`
    FOREIGN KEY (`doctorId`)
    REFERENCES `mydb`.`Doctor` (`doctorId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Doctor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Doctor` (
  `userId` VARCHAR(10) NOT NULL,
  `doctorId` VARCHAR(10) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `role` ENUM('DOCTOR', 'PHYSICIAN', 'RECEPTIONIST', 'PATIENT', 'USER') NOT NULL DEFAULT 'USER',
  `lastLogin` DATETIME NOT NULL,
  `isActive` TINYINT NOT NULL,
  `passwordExpDate` DATE NOT NULL,
  `dailyNotification` VARCHAR(45) NULL,
  PRIMARY KEY (`userId`, `doctorId`),
  UNIQUE INDEX `doctorId_UNIQUE` (`doctorId` ASC) VISIBLE,
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MedicalRecord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MedicalRecord` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MedicalRecord` (
  `recordId` VARCHAR(10) NOT NULL,
  `patientId` VARCHAR(10) NOT NULL,
  `doctorId` VARCHAR(10) NOT NULL,
  `symptoms` VARCHAR(100) NOT NULL,
  `diagnosis` VARCHAR(50) NOT NULL,
  `treatment` VARCHAR(50) NOT NULL,
  `notes` JSON NULL,
  PRIMARY KEY (`recordId`, `patientId`, `doctorId`),
  UNIQUE INDEX `recordId_UNIQUE` (`recordId` ASC) VISIBLE,
  INDEX `diagnosis_idx` (`diagnosis` ASC) VISIBLE,
  CONSTRAINT `diagnosis`
    FOREIGN KEY (`diagnosis`)
    REFERENCES `mydb`.`PrescriptionItem` (`prescriptionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Medication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Medication` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Medication` (
  `medicationId` VARCHAR(10) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `genericName` VARCHAR(50) NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `stockQuantity` INT NOT NULL,
  `mininumStockLevel` INT NOT NULL,
  `expirationDate` DATETIME NOT NULL,
  `sideEffects` VARCHAR(100) NULL,
  `contraindication` VARCHAR(100) NULL,
  PRIMARY KEY (`medicationId`),
  UNIQUE INDEX `medicationId_UNIQUE` (`medicationId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Patient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Patient` (
  `userId` VARCHAR(10) NOT NULL,
  `patientId` VARCHAR(10) NOT NULL,
  `height` FLOAT NOT NULL,
  `weight` FLOAT NOT NULL,
  `bloodType` ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-') NOT NULL,
  `allergies` JSON NULL,
  `insuranceInfo` JSON NOT NULL,
  `emergencyContact` VARCHAR(16) NULL,
  PRIMARY KEY (`userId`, `patientId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `patientId_UNIQUE` (`patientId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pharmacist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pharmacist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pharmacist` (
  `userId` VARCHAR(10) NOT NULL,
  `pharmacistId` VARCHAR(10) NOT NULL,
  `licenseId` VARCHAR(10) NOT NULL,
  `yearsExperience` INT NOT NULL,
  `speciality` VARCHAR(50) NOT NULL,
  `isAvailable` TINYINT NOT NULL,
  PRIMARY KEY (`userId`, `pharmacistId`),
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Prescription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Prescription` (
  `prescriptionId` VARCHAR(10) NOT NULL,
  `patientId` VARCHAR(10) NOT NULL,
  `doctorId` VARCHAR(10) NOT NULL,
  `itemId` VARCHAR(10) NULL,
  `date` DATETIME NOT NULL,
  `instruction` VARCHAR(50) NOT NULL,
  `diagnosis` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`prescriptionId`, `patientId`, `doctorId`),
  UNIQUE INDEX `recordId_UNIQUE` (`prescriptionId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PrescriptionItem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PrescriptionItem` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PrescriptionItem` (
  `prescriptionId` VARCHAR(10) NOT NULL,
  `itemId` VARCHAR(10) NOT NULL,
  `dosage` INT NOT NULL,
  `frequency` INT NOT NULL,
  `duration` VARCHAR(50) NOT NULL,
  `notes` JSON NOT NULL,
  PRIMARY KEY (`prescriptionId`, `itemId`),
  UNIQUE INDEX `recordId_UNIQUE` (`prescriptionId` ASC) VISIBLE,
  CONSTRAINT `prescription`
    FOREIGN KEY (`prescriptionId`)
    REFERENCES `mydb`.`Prescription` (`prescriptionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Receptionist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Receptionist` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Receptionist` (
  `userId` VARCHAR(10) NOT NULL,
  `receptionistId` VARCHAR(10) NOT NULL,
  `station` VARCHAR(50) NOT NULL,
  `status` ENUM('ACTIVE', 'NONACTIVE') NOT NULL,
  `officePhone` VARCHAR(16) NOT NULL,
  `shiftStartTime` DATETIME NOT NULL,
  `shiftEndTime` DATETIME NOT NULL,
  PRIMARY KEY (`userId`, `receptionistId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `receptionistId_UNIQUE` (`receptionistId` ASC) VISIBLE,
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userId` VARCHAR(10) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `role` VARCHAR(12) NOT NULL,
  `lastLogin` DATETIME NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `isActive` TINYINT NOT NULL,
  `passwordExpDate` DATETIME NOT NULL,
  `dailyNotification` VARCHAR(100) NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
